# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('api_cmd', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('parser', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('param_type', models.CharField(choices=[('station', 'station'), ('dir', 'dir')], max_length=40)),
                ('commands', models.ManyToManyField(to='bart.Command')),
            ],
        ),
    ]
