# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0002_auto_20161211_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='default_value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
