# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0005_parameter_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='param_type',
            field=models.CharField(choices=[('station', 'station'), ('dir', 'dir'), ('num_trains', 'num_trains'), ('command', 'command')], max_length=40),
        ),
    ]
