# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0006_auto_20161212_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
