# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0008_auto_20161215_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='id',
        ),
        migrations.AlterField(
            model_name='station',
            name='key',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
