# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0009_auto_20161222_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='aliases',
        ),
        migrations.AddField(
            model_name='stationalias',
            name='station',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bart.Station'),
            preserve_default=False,
        ),
    ]
