# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0010_auto_20161222_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='parser',
            new_name='formatter',
        ),
    ]
