# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0011_auto_20161222_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='head_station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='hex_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
