# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0013_auto_20161222_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='lines',
        ),
        migrations.AddField(
            model_name='line',
            name='lines',
            field=models.ManyToManyField(to='bart.Station'),
        ),
    ]
