# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bart', '0014_auto_20161222_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='lines',
            new_name='stations',
        ),
    ]
